name: Deploy to Cloudflare R2

on:
  push:
    branches: [ iptv ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload to R2
        uses: yofix/storage@main
        with:
          provider: r2
          files: './**/*'
          account-id: ${{ secrets.R2_ACCOUNT_ID }}
          bucket: iptv
          access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          base-path: ''
          verbose: true